# Netlify 的主要建置設定
[build]
  # 注意：我們移除了 base = "frontend/" 這一行！
  
  # Build command: 從根目錄執行，我們先 cd 進入 frontend，完成工作後再回來
  command = "cd frontend && npm install && npm run build"
  
  # Publish directory: 發布目錄的路徑必須從根目錄算起
  publish = "frontend/dist/"
  
  # Functions directory: 函數目錄的路徑也從根目錄算起
  functions = "netlify/functions/"

# --- 重定向規則 (這部分保持不變) ---

# 規則一：API 代理
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 規則二：單頁應用 (SPA) 回退規則
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200